blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:blog_id>', views.detail, name='detail'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

blogs/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(blank=False, null=False, max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blogs/views.py
from django.shortcuts import render
from .models import Blog

def index(request):
    blogs = Blog.objects.order_by('-created_datetime')
    context = {
        'title': 'Blog Site',
        'msg': 'Here is a top page.',
        'blg': blogs,
    }

    return render(request, 'blogs/index.html', context)

def detail(request, blog_id):
    blog =Blog.objects.get(id=blog_id)
    context = {
        'title': 'Blog Application',
        'blg': blog,
    }
    return render(request, 'blogs/detail.html', context)

blogs/templates/blogs/detail.html
<!Doctype html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1 style="text-align: center;">{{ blg.title }}</h1>
    <div style="width: 70%; margin: 0px auto;">
        <div>
            <div style="margin: 60px 20px;">
                {{ blg.text }}
            </div>
            <div style="text-align: center; margin-top: 50px;">
                <a href="{% url 'blogs:index' %}">Return Top</a>
            </div>
        </div>
    </div>
</body>
</html>

blogs/templates/blogs/index.html
<!Doctype html>
<html>
<head>
    <title>{{title}}</title>
</head>
<body>
    <h1 style="text-align: center;">{{ title }}</h1>
    <div style="width: 70%; margin: 0px auto;">{{ msg }}
        <hr>
        {% for b in blg %}
        <div>
            <h3>{{ b.title }}</h3>
            <div>{{ b.text | truncatechars:100 }}</div>
            <div style="text-align: right;">
                <a href="{% url 'blogs:detail' blog_id=b.id %}">Read article</a>
            </div>
        </div>
        <hr>
        {% endfor %}
    </div>
</body>
</html>